### ISSUE TITLE
When BLE ACM is unplugged and then replugged application does not automatically reconnect

### ISSUE THREAD

**Issue by MylesCaley** [FirstBuild/FirstBuild-Mobile#11]
If the ACM is unplugged (it will show red banner indicating disconnection) the iOS will be in reconnecting mode but will sometimes fail. If the BLE ACM has power cycled multiple times the iOS app will eventually reconnect.

**Comment by jeffddrake** [comment]
I tested this for several hours with probably over 100 power cycles (ok probably an hour and only 50 ish power cycles) today with the latest firmware, no issue. Myles I will let you close this when you think it's ok to close. There were some times when the app took longer to reconnect, but it always reconnected.
