### ISSUE TITLE
Elapsed time is not working correctly. 

### ISSUE THREAD

**Issue by MylesCaley** [FirstBuild/FirstBuild-Mobile#16]
Most of the time, 998142D1-658E-33E2-DFC0-32091E2354EC, is reading 0x0000. When it does appear to be working it increments in minutes start with 0x0100, 0x0200, etc. Is the endianess backward. It also appears to continue counting even if a cook mode has stopped.

**Comment by jeffddrake** [comment]
This is now fixed. I just re-wrote most of the function on how elapsed time is calculated and tested the feature with an Android app. 
The endianness and the feature now work properly, some things have changed though.

When you start sous vide on the cooktop the timer is cleared to 0 and then started to increment every minute. As it increments you will get a notification.
When you stop sous vide on this particular burner it then latches the elapsed time value. This value isn't cleared until the next sous vide cycle starts.
