### ISSUE TITLE
There is no time-out when Paragon App CAN not find Paragon unit

### ISSUE THREAD

**Issue by Zenah** [FirstBuild/FirstBuild-Mobile#18]
Open App > Hit 'settings' on Blue tooth setting pop-up > Do not turn on Blue tooth > Open Paragon App again > Hit ADD PRODUCT > Hit Paragon 
There is no time-out when Paragon App CAN not find Paragon unit.
'Searching for your Paragon..' page shows endless.

**Comment by MylesCaley** [comment]
@Zenah we added a back button to the screen which will allow the user to cancel when they want.
